### PR TITLE
KCE-68 Remove completely DDS from kpsr-core

### PR DESCRIPTION
**Pull request by joseluisbf-kpsr**
### Questions
1. Is it required to update `version.cpp`?
2. Should I wait until merge [KCE-68 Remove completely DDS from kpsr-build](https://github.com/klepsydra-technologies/kpsr-build/pull/20)?
    The goal is to point to the the last `kpsr-build` _submodule_ version.

### TODO
- `code_generator/` -> will be addressed by @tomasz3dk (2023-04-05 daily meeting)
- `api-doc/`: `make doc` generates almost empty .md files -> unchanged
- `.github/workflows/`
- kpsr-build: its own repo -> branch KCE-68, see PR [KCE-68 Remove completely DDS from kpsr-build #20](https://github.com/klepsydra-technologies/kpsr-build/pull/20)

### CODE REVIEW

**Comment by joseluisbf-kpsr** [comment]
TODO
- code_generator/
- api-doc/ : `make doc` generates almost empty .md files
- (kpsr-build: its own repo)

**Review by pablogh-2000 — APPROVED** [review]
Good PR!. Please accompany this with the removal of the DDS files in kpsr-build

**Comment by joseluisbf-kpsr** [comment]
Is it required to update `version.cpp`?

**Comment by joseluisbf-kpsr** [comment]
Should I wait until merge [KCE-68 Remove completely DDS from kpsr-build](https://github.com/klepsydra-technologies/kpsr-build/pull/20)?
The goal is to point to the the last `kpsr-build` _submodule_ version.

**Comment by mharshe** [comment]
Please rebase this to main. Although I think that you have already included these changes into the PR https://github.com/klepsydra-technologies/kpsr-core/pull/93/files so this PR may not be necessary.

**Comment by joseluisbf-kpsr** [comment]
Waiting for [KCE-68](https://github.com/klepsydra-technologies/kpsr-build/pull/20) merge of submodule `kpsr-build`.

**Pull request merged**
